services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    # Run via uv so we don't depend on uvicorn CLI being on PATH
    command: >
      sh -lc 'uv run main.py'
    expose:
      - "8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - HF_HOME=/cache/hf
    volumes:
      - hf_cache:/cache/hf
    healthcheck:
      # use python3 (always present) to hit /health
      test: ["CMD", "python3", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2).read(); sys.exit(0)"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [appnet]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [appnet]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  appnet:

volumes:
  hf_cache:
